version: 2.1
jobs:
  build_docker:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup .ENV file
          command: |
            cat \<< EOF > .env
            DB_PASSWORD=password
            DB_HOST=database
            DB_NAME=dbname
            DB_USER=dbuser
            DATABASE_URL_DEV=postgresql://dbuser:password@database/dbname
            PRIVATE_KEY_WIF=L4zjyPeL2DDzytJdJCxbndy1BukrcuLVLXNqdGqzKhyCkATPZnUv
            EOF
      - run:
          name: Startup docker
          command: docker-compose up -d
      - run:
          name: Run Tests
          command: docker-compose run stratum npm test
      - run:
          name: Report Code Coverage
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov
      - run:
          name: Build docker image
          command: docker build -t boost-stratum . 
      - run:
          name: Push to Docker Hub
          command: |
            docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
            docker tag boost-stratum proofofwork/boost-stratum:$CIRCLE_BRANCH
            docker push proofofwork/boost-stratum:$CIRCLE_BRANCH

  deploy:
    machine: true
    steps:
      - run:
          name: Deploy to Web Servers
          command: ssh ubuntu@pow.co "sudo chef-client -o recipe[pow.co::boost_stratum]"


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_docker
      - deploy:
          requires:
            - build_docker
          filters:
            branches:
              only:
                - master

